#!/bin/bash
# Generated by lab8_1.sh for AWS Academy Lab 8.1

set -euo pipefail

REGION="us-east-1"
CODE_URL="https://aws-tc-largeobjects.s3.us-west-2.amazonaws.com/CUR-TF-200-ACCDEV-2-91558/06-lab-containers/code.zip"
MYSQL_PUBLIC_IP="3.84.93.120"
LABIDE_PUBLIC_IP="23.23.135.21"
ECR_REPO_NAME="node-app"
BASE="$HOME/environment"
NODE_DIR="$BASE/containers/node_app/codebase_partner"
MYSQL_DIR="$BASE/containers/mysql"

wait_for_http() {
  local url="$1"
  local retries="${2:-90}"
  local count=0

  until curl -fsS "$url" > /dev/null 2>&1; do
    count=$((count + 1))
    if [ "$count" -ge "$retries" ]; then
      echo "ERROR: Timed out waiting for $url" >&2
      exit 1
    fi
    sleep 2
  done
}

echo ""
echo "===> [Task 1] Downloading lab files..."
mkdir -p "$BASE"
cd "$BASE"
if [ ! -f code.zip ]; then
  wget -q "$CODE_URL" -O code.zip
fi
unzip -o code.zip > /dev/null 2>&1 || true

echo "===> [Task 1] Running setup.sh..."
chmod +x ./resources/setup.sh
./resources/setup.sh

echo "===> [Task 1] Verifying tools..."
aws --version
pip3 show boto3 > /dev/null

echo ""
echo "===> [Task 3] Preparing node_app workspace..."
mkdir -p "$BASE/containers/node_app"
if [ ! -d "$NODE_DIR" ]; then
  cp -R "$BASE/resources/codebase_partner" "$BASE/containers/node_app/"
fi

cat > "$NODE_DIR/Dockerfile" <<'DOCKERFILE'
FROM node:11-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .
RUN npm install
EXPOSE 3000
CMD ["npm", "run", "start"]
DOCKERFILE

echo "===> [Task 3] Building node_app image..."
cd "$NODE_DIR"
docker build --tag node_app .

echo "===> [Task 3] Starting node_app_1 against MysqlServerNode..."
docker stop node_app_1 2>/dev/null || true
docker rm node_app_1 2>/dev/null || true
docker run -d --name node_app_1 -p 3000:3000 -e APP_DB_HOST="$MYSQL_PUBLIC_IP" node_app > /dev/null
wait_for_http "http://localhost:3000" 45
echo "    node_app_1 is responding on localhost:3000."

echo ""
echo "===> [Task 4] Dumping MySQL data from MysqlServerNode..."
mkdir -p "$MYSQL_DIR"
mysqldump -P 3306 -h "$MYSQL_PUBLIC_IP" -u nodeapp -pcoffee   --databases COFFEE > "$MYSQL_DIR/my_sql.sql"
echo "    Dump created at $MYSQL_DIR/my_sql.sql"

if grep -q 'Main' "$MYSQL_DIR/my_sql.sql"; then
  sed -i '0,/Main/s//Container/' "$MYSQL_DIR/my_sql.sql"
  echo "    Updated the first 'Main' occurrence in the dump to 'Container'."
fi

cat > "$MYSQL_DIR/Dockerfile" <<'DOCKERFILE'
FROM mysql:8.0.23
COPY ./my_sql.sql /
EXPOSE 3306
DOCKERFILE

echo "===> [Task 4] Freeing unused Docker space..."
docker image prune -af > /dev/null 2>&1 || true
docker container prune -f > /dev/null 2>&1 || true

echo "===> [Task 4] Building mysql_server image..."
cd "$MYSQL_DIR"
docker build --tag mysql_server .

echo "===> [Task 4] Starting mysql_1..."
docker stop mysql_1 2>/dev/null || true
docker rm mysql_1 2>/dev/null || true
docker run --name mysql_1 -p 3306:3306 -e MYSQL_ROOT_PASSWORD=rootpw -d mysql_server > /dev/null

echo "    Waiting for MySQL to initialize..."
for _ in $(seq 1 36); do
  if docker exec mysql_1 mysqladmin ping -u root -prootpw --silent > /dev/null 2>&1; then
    break
  fi
  sleep 5
done

if ! docker exec mysql_1 mysqladmin ping -u root -prootpw --silent > /dev/null 2>&1; then
  echo "ERROR: mysql_1 did not become ready in time." >&2
  exit 1
fi

docker exec -i mysql_1 mysql -u root -prootpw -e "DROP DATABASE IF EXISTS COFFEE;"
sed -i '1d' "$MYSQL_DIR/my_sql.sql"
docker exec -i mysql_1 mysql -u root -prootpw < "$MYSQL_DIR/my_sql.sql"
docker exec -i mysql_1 mysql -u root -prootpw -e   "CREATE USER IF NOT EXISTS 'nodeapp' IDENTIFIED WITH mysql_native_password BY 'coffee'; GRANT ALL PRIVILEGES ON *.* TO 'nodeapp'@'%'; FLUSH PRIVILEGES;"
echo "    mysql_1 seeded and nodeapp user created."

echo ""
echo "===> [Task 5] Reconnecting node_app_1 to mysql_1..."
MYSQL_CONTAINER_IP="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql_1)"
docker stop node_app_1 > /dev/null 2>&1 || true
docker rm node_app_1 > /dev/null 2>&1 || true
docker run -d --name node_app_1 -p 3000:3000 -e APP_DB_HOST="$MYSQL_CONTAINER_IP" node_app > /dev/null
sleep 10
wait_for_http "http://localhost:3000" 45
echo "    node_app_1 is now using mysql_1 at $MYSQL_CONTAINER_IP."

echo ""
echo "===> [Task 6] Pushing node_app to ECR..."
ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text --region "$REGION")"
ECR_REGISTRY="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com"

if ! aws ecr describe-repositories --repository-names "$ECR_REPO_NAME" --region "$REGION" > /dev/null 2>&1; then
  aws ecr create-repository --repository-name "$ECR_REPO_NAME" --region "$REGION" > /dev/null
fi

ECR_URI="$(aws ecr describe-repositories --repository-names "$ECR_REPO_NAME" --region "$REGION" --query 'repositories[0].repositoryUri' --output text)"
aws ecr get-login-password --region "$REGION" | docker login --username AWS --password-stdin "$ECR_REGISTRY"
docker tag node_app:latest "$ECR_URI:latest"
docker push "$ECR_URI:latest"

echo ""
echo "===> [Task 6] Verifying ECR image..."
aws ecr list-images --repository-name "$ECR_REPO_NAME" --region "$REGION"

echo ""
echo "===> Running containers:"
docker ps

echo ""
echo "=== Lab 8.1 LabIDE setup COMPLETE ==="
echo "    App URL: http://$LABIDE_PUBLIC_IP:3000"
echo "    ECR repo: $ECR_URI"
