#!/bin/bash
# Generated by lab8_2.sh for AWS Academy Lab 8.2

set -euo pipefail

REGION="us-east-1"
CODE_URL="https://aws-tc-largeobjects.s3.us-west-2.amazonaws.com/CUR-TF-200-ACCDEV-2-91558/07-lab-deploy/code.zip"
PUBLIC_IP="176.46.249.8"
DB_ENDPOINT="supplierdb.cluster-csn3dsr3mlw3.us-east-1.rds.amazonaws.com"
LABIDE_PUBLIC_IP="18.205.166.227"
IDE_VPC_ID="vpc-0946d75a6fdb6be2a"
IDE_AZ="us-east-1a"
IDE_SUBNET_ID="subnet-0301308d0c6ceac61"
EXTRA_SUBNET_ID="subnet-017aada0e7e6565ab"
LABIDE_SG="sg-01a134e3b87b90ee5"
RDS_CLUSTER_ID="supplierdb"
RDS_MASTER_USERNAME="admin"
RDS_MASTER_PASSWORD="coffee_beans_for_all"
RDS_APP_USERNAME="nodeapp"
RDS_APP_PASSWORD="coffee"
ECR_REPO_NAME="cafe/node-web-app"
EB_APPLICATION_NAME="MyNodeApp"
EB_ENVIRONMENT_NAME="MyEnv"
HELPER_BUCKET="lab8-2-setup-976339170106-us-east-1"
BASE="$HOME/environment"
VALUES_FILE="$BASE/lab8_2_values.txt"

wait_for_http() {
  local url="$1"
  local retries="${2:-90}"
  local count=0

  until curl -fsS "$url" > /dev/null 2>&1; do
    count=$((count + 1))
    if [ "$count" -ge "$retries" ]; then
      echo "ERROR: Timed out waiting for $url" >&2
      exit 1
    fi
    sleep 2
  done
}

wait_for_mysql() {
  local retries="${1:-90}"
  local count=0

  until mysql -h "$DB_ENDPOINT" -P 3306 -u "$RDS_MASTER_USERNAME" -p"$RDS_MASTER_PASSWORD" -e "SELECT 1" > /dev/null 2>&1; do
    count=$((count + 1))
    if [ "$count" -ge "$retries" ]; then
      echo "ERROR: Timed out waiting for MySQL at $DB_ENDPOINT" >&2
      exit 1
    fi
    sleep 10
  done
}

wait_for_eb_ready() {
  local retries="${1:-90}"
  local count=0
  local status
  local health
  local cname

  while true; do
    status=$(aws elasticbeanstalk describe-environments       --region "$REGION"       --application-name "$EB_APPLICATION_NAME"       --environment-names "$EB_ENVIRONMENT_NAME"       --query 'Environments[0].Status'       --output text 2>/dev/null || true)
    health=$(aws elasticbeanstalk describe-environments       --region "$REGION"       --application-name "$EB_APPLICATION_NAME"       --environment-names "$EB_ENVIRONMENT_NAME"       --query 'Environments[0].Health'       --output text 2>/dev/null || true)
    cname=$(aws elasticbeanstalk describe-environments       --region "$REGION"       --application-name "$EB_APPLICATION_NAME"       --environment-names "$EB_ENVIRONMENT_NAME"       --query 'Environments[0].CNAME'       --output text 2>/dev/null || true)

    if [ "$status" = "Ready" ] && [ -n "$cname" ] && [ "$cname" != "None" ]; then
      echo "    Elastic Beanstalk status: $status / $health" >&2
      printf '%s\n' "$cname"
      return 0
    fi

    count=$((count + 1))
    if [ "$count" -ge "$retries" ]; then
      echo "ERROR: Timed out waiting for Elastic Beanstalk environment $EB_ENVIRONMENT_NAME" >&2
      exit 1
    fi

    echo "    Waiting for Elastic Beanstalk: status=${status:-unknown}, health=${health:-unknown}" >&2
    sleep 20
  done
}

write_values_file() {
  local repository_uri="$1"
  local eb_url="$2"
  local website_url="$3"

  cat > "$VALUES_FILE" <<VALUES
IDE VPC ID: $IDE_VPC_ID
IDE Availability Zone: $IDE_AZ
IDE subnet ID: $IDE_SUBNET_ID
extraSubnetForRds subnet ID: $EXTRA_SUBNET_ID
IDE security group ID: $LABIDE_SG
Database endpoint: $DB_ENDPOINT
Repository URI: $repository_uri
Elastic Beanstalk URL: $eb_url
WebsiteURL: $website_url
VALUES
}

echo ""
echo "==> [Task 1] Downloading lab files..."
mkdir -p "$BASE"
cd "$BASE"
if [ ! -f code.zip ]; then
  wget -q "$CODE_URL" -O code.zip
fi
unzip -o code.zip > /dev/null 2>&1 || true

echo "==> [Task 1] Running setup.sh..."
chmod +x ./resources/setup.sh
read -rp "Public IPv4 for setup.sh [$PUBLIC_IP]: " IP_FOR_SETUP
IP_FOR_SETUP="${IP_FOR_SETUP:-$PUBLIC_IP}"
printf '%s\n' "$IP_FOR_SETUP" | ./resources/setup.sh

echo "==> [Task 1] Verifying AWS CLI and boto3..."
aws --version
pip3 show boto3 > /dev/null

S3_BUCKET=$(aws s3api list-buckets   --query "Buckets[?contains(Name, '-s3bucket')].Name | [0]"   --output text 2>/dev/null || true)
WEBSITE_URL=""
if [ -n "$S3_BUCKET" ] && [ "$S3_BUCKET" != "None" ]; then
  WEBSITE_URL="http://${S3_BUCKET}.s3-website-${REGION}.amazonaws.com"
fi

echo ""
echo "==> [Task 4] Reviewing the ECR image..."
aws ecr describe-repositories --region "$REGION"
aws ecr describe-images --region "$REGION" --repository-name "$ECR_REPO_NAME"
REPOSITORY_URI=$(aws ecr describe-repositories   --region "$REGION"   --repository-names "$ECR_REPO_NAME"   --query 'repositories[0].repositoryUri'   --output text)

echo ""
echo "==> [Task 5] Starting the container against Aurora..."
docker stop node-web-app-1 > /dev/null 2>&1 || true
docker rm node-web-app-1 > /dev/null 2>&1 || true
docker run -d --name node-web-app-1 -p 8000:3000 -e APP_DB_HOST="$DB_ENDPOINT" "$ECR_REPO_NAME" > /dev/null
wait_for_http "http://localhost:8000" 60
curl -fsS http://localhost:8000 > /dev/null
echo "    Container is responding on http://localhost:8000"
echo "    Browser URL: http://$LABIDE_PUBLIC_IP:8000"

echo ""
echo "==> [Task 6] Preparing the exact grader-sensitive commands..."
wait_for_mysql 60
cat > "$BASE/lab8_2_task6_query_editor.sql" <<'TASK6SQL'
DROP USER IF EXISTS 'nodeapp'@'%';
DROP DATABASE IF EXISTS COFFEE;

CREATE USER 'nodeapp'@'%' IDENTIFIED WITH mysql_native_password BY 'coffee';
CREATE DATABASE COFFEE;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER ON *.* TO 'nodeapp'@'%' WITH GRANT OPTION;

USE COFFEE;

CREATE TABLE suppliers(
    id INT NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(100) NOT NULL,
    PRIMARY KEY (id)
);

SELECT * FROM suppliers;
TASK6SQL

cat > "$BASE/lab8_2_task7_mysql_commands.txt" <<TASK7CMDS
cd ~/environment/resources
mysql -h $DB_ENDPOINT -P 3306 -u admin -p
# Password: coffee_beans_for_all
use COFFEE;
source coffee_db_dump.sql
select count(*) from suppliers;
select count(*) from beans;
exit
TASK7CMDS

echo "    Task 6 must be done in AWS RDS Query Editor for reliable grading."
echo ""
echo "    In the AWS console:"
echo "    1. Open RDS -> Query Editor."
echo "    2. Connect with:"
echo "       Cluster/schema: supplierdb / suppliers"
echo "       Username: admin"
echo "       Password: coffee_beans_for_all"
echo "    3. Paste and run the SQL saved at:"
echo "       $BASE/lab8_2_task6_query_editor.sql"
echo ""
echo "    Exact SQL to paste:"
echo "------------------------------------------------------------"
cat "$BASE/lab8_2_task6_query_editor.sql"
echo "------------------------------------------------------------"
echo ""
echo "    Then open this page in the browser:"
echo "       http://$LABIDE_PUBLIC_IP:8000/suppliers"
echo "    Add one supplier through the website UI."
read -rp "Press ENTER after Task 6 is done in Query Editor and one supplier was added..."

echo ""
echo "==> [Task 6] Verifying the supplier row..."
mysql -h "$DB_ENDPOINT" -P 3306 -u "$RDS_MASTER_USERNAME" -p"$RDS_MASTER_PASSWORD" -e "USE COFFEE; SELECT * FROM suppliers;"

echo ""
echo "==> [Task 7] Manual seed step required for reliable grading..."
echo "    Open a SECOND LabIDE terminal and run these exact commands:"
echo "------------------------------------------------------------"
cat "$BASE/lab8_2_task7_mysql_commands.txt"
echo "------------------------------------------------------------"
echo ""
echo "    Do not type <db-endpoint>; the real endpoint is already in the command above."
read -rp "Press ENTER after you ran the Task 7 commands in the second LabIDE terminal..."
mysql -h "$DB_ENDPOINT" -P 3306 -u "$RDS_MASTER_USERNAME" -p"$RDS_MASTER_PASSWORD" -e "USE COFFEE; SELECT COUNT(*) AS suppliers_count FROM suppliers; SELECT COUNT(*) AS beans_count FROM beans;"
echo "    Supplier and beans data verified."

echo ""
echo "==> [Task 9] Creating the Elastic Beanstalk application..."
cd "$BASE"
mkdir -p bean
cd bean

cat > options.txt <<OPTIONS
[
    {
        "Namespace": "aws:autoscaling:launchconfiguration",
        "OptionName": "IamInstanceProfile",
        "Value": "aws-elasticbeanstalk-ec2-role"
    },
    {
        "Namespace": "aws:autoscaling:launchconfiguration",
        "OptionName": "SecurityGroups",
        "Value": "$LABIDE_SG"
    },
    {
        "Namespace": "aws:ec2:vpc",
        "OptionName": "VPCId",
        "Value": "$IDE_VPC_ID"
    },
    {
        "Namespace": "aws:ec2:vpc",
        "OptionName": "Subnets",
        "Value": "$IDE_SUBNET_ID,$EXTRA_SUBNET_ID"
    },
    {
        "Namespace": "aws:elasticbeanstalk:application:environment",
        "OptionName": "APP_DB_HOST",
        "Value": "$DB_ENDPOINT"
    }
]
OPTIONS

if ! aws elasticbeanstalk describe-applications   --region "$REGION"   --application-names "$EB_APPLICATION_NAME"   --query 'Applications[0].ApplicationName'   --output text 2>/dev/null | grep -Fxq "$EB_APPLICATION_NAME"; then
  aws elasticbeanstalk create-application     --region "$REGION"     --application-name "$EB_APPLICATION_NAME" > /dev/null
fi

SOLUTION_STACK=$(aws elasticbeanstalk list-available-solution-stacks   --region "$REGION"   --query "SolutionStacks[?contains(@, 'Amazon Linux 2') && contains(@, 'running Docker')]"   --output text | tr '\t' '\n' | tail -n 1)

if [ -z "$SOLUTION_STACK" ]; then
  echo "ERROR: Could not find an Amazon Linux 2 Docker solution stack." >&2
  exit 1
fi

if ! aws elasticbeanstalk describe-environments   --region "$REGION"   --application-name "$EB_APPLICATION_NAME"   --environment-names "$EB_ENVIRONMENT_NAME"   --query "Environments[?Status!='Terminated'][0].EnvironmentName"   --output text 2>/dev/null | grep -Fxq "$EB_ENVIRONMENT_NAME"; then
  aws elasticbeanstalk create-environment     --region "$REGION"     --application-name "$EB_APPLICATION_NAME"     --environment-name "$EB_ENVIRONMENT_NAME"     --solution-stack-name "$SOLUTION_STACK"     --option-settings file://options.txt > /dev/null
fi

EB_CNAME=$(wait_for_eb_ready 90)
echo "    Sample environment URL: http://$EB_CNAME"

cat > Dockerrun.aws.json <<DOCKERRUN
{
  "AWSEBDockerrunVersion": "1",
  "Image": {
    "Name": "$REPOSITORY_URI",
    "Update": "true"
  },
  "Ports": [
    {
      "ContainerPort": 3000
    }
  ]
}
DOCKERRUN

VERSION_LABEL="${EB_APPLICATION_NAME}-version-$(date +%Y%m%d%H%M%S)a"
ZIP_NAME="${VERSION_LABEL}.zip"
rm -f "$ZIP_NAME"
if command -v zip > /dev/null 2>&1; then
  zip -q -j "$ZIP_NAME" Dockerrun.aws.json
else
  python3 - <<PY
import zipfile
with zipfile.ZipFile("${ZIP_NAME}", "w", compression=zipfile.ZIP_DEFLATED) as zf:
    zf.write("Dockerrun.aws.json", arcname="Dockerrun.aws.json")
PY
fi
aws s3 cp "$ZIP_NAME" "s3://$HELPER_BUCKET/$ZIP_NAME" > /dev/null

aws elasticbeanstalk create-application-version   --region "$REGION"   --application-name "$EB_APPLICATION_NAME"   --version-label "$VERSION_LABEL"   --source-bundle S3Bucket="$HELPER_BUCKET",S3Key="$ZIP_NAME"   --process > /dev/null

aws elasticbeanstalk update-environment   --region "$REGION"   --environment-name "$EB_ENVIRONMENT_NAME"   --version-label "$VERSION_LABEL" > /dev/null

EB_CNAME=$(wait_for_eb_ready 90)
docker stop node-web-app-1 > /dev/null 2>&1 || true
docker rm node-web-app-1 > /dev/null 2>&1 || true

write_values_file "$REPOSITORY_URI" "http://$EB_CNAME" "$WEBSITE_URL"

echo ""
echo "==> [Task 9] Verifying the deployed application..."
wait_for_http "http://$EB_CNAME/beans.json" 60
echo "    Elastic Beanstalk URL: http://$EB_CNAME"
echo "    Values file: $VALUES_FILE"

echo ""
echo "=== Lab 8.2 LabIDE setup COMPLETE ==="
echo "    LabIDE app URL:        http://$LABIDE_PUBLIC_IP:8000"
echo "    Elastic Beanstalk URL: http://$EB_CNAME"
if [ -n "$WEBSITE_URL" ]; then
  echo "    Cafe Website URL:      $WEBSITE_URL"
fi
echo "    Next: return to your original terminal and press ENTER."
