#!/bin/bash
# Lab 8.1: Migrating a Web Application to Docker Containers

source ./common.sh

set -euo pipefail

REGION="${AWS_REGION:-$AWS_DEFAULT_REGION}"
CODE_URL="https://aws-tc-largeobjects.s3.us-west-2.amazonaws.com/CUR-TF-200-ACCDEV-2-91558/06-lab-containers/code.zip"
ECR_REPO_NAME="node-app"
LABIDE_SCRIPT="./lab8_labide_setup.generated.sh"
HELPER_OBJECT="$(basename "$LABIDE_SCRIPT")"

require_value() {
  local value="$1"
  local label="$2"

  if [ -z "$value" ] || [ "$value" = "None" ]; then
    echo "ERROR: Could not determine $label." >&2
    exit 1
  fi
}

find_instance_info() {
  local name_values="$1"

  aws ec2 describe-instances \
    --region "$REGION" \
    --filters "Name=tag:Name,Values=$name_values" \
              "Name=instance-state-name,Values=running" \
    --query 'Reservations[].Instances[].[InstanceId,PublicIpAddress,SecurityGroups[0].GroupId]' \
    --output text | head -n 1
}

ensure_port_3000_for_my_ip() {
  local security_group_id="$1"
  local cidr="$2"
  local existing

  existing=$(aws ec2 describe-security-groups \
    --region "$REGION" \
    --group-ids "$security_group_id" \
    --query "SecurityGroups[0].IpPermissions[?FromPort==\`3000\` && ToPort==\`3000\`].IpRanges[?CidrIp=='$cidr'].CidrIp" \
    --output text 2>/dev/null || true)

  if echo "$existing" | tr '\t' '\n' | grep -Fxq "$cidr"; then
    echo "    Port 3000 already open for $cidr on $security_group_id."
    return
  fi

  if aws ec2 authorize-security-group-ingress \
    --region "$REGION" \
    --group-id "$security_group_id" \
    --protocol tcp \
    --port 3000 \
    --cidr "$cidr" > /dev/null 2>&1; then
    echo "    Port 3000 opened for $cidr on $security_group_id."
  else
    echo "    WARNING: Could not open port 3000 on $security_group_id. Check the rule manually in EC2."
  fi
}

ensure_mysql_port_best_effort() {
  local instance_id="$1"
  local security_group_ids

  security_group_ids=$(aws ec2 describe-instances \
    --region "$REGION" \
    --instance-ids "$instance_id" \
    --query 'Reservations[0].Instances[0].SecurityGroups[*].GroupId' \
    --output text 2>/dev/null || true)

  for security_group_id in $security_group_ids; do
    if aws ec2 authorize-security-group-ingress \
      --region "$REGION" \
      --group-id "$security_group_id" \
      --protocol tcp \
      --port 3306 \
      --cidr "0.0.0.0/0" > /dev/null 2>&1; then
      echo "    Port 3306 opened on $security_group_id."
    else
      echo "    Port 3306 already open or not editable on $security_group_id."
    fi
  done
}

create_staging_bucket() {
  local bucket_name="lab8-setup-${ACCOUNT_ID}-${REGION}"

  if aws s3api head-bucket --bucket "$bucket_name" > /dev/null 2>&1; then
    printf '%s\n' "$bucket_name"
    return 0
  fi

  if [ "$REGION" = "us-east-1" ]; then
    aws s3api create-bucket \
      --bucket "$bucket_name" \
      --region "$REGION" > /dev/null
  else
    aws s3api create-bucket \
      --bucket "$bucket_name" \
      --region "$REGION" \
      --create-bucket-configuration "LocationConstraint=$REGION" > /dev/null
  fi

  printf '%s\n' "$bucket_name"
}

upload_helper_script() {
  local bucket_name

  bucket_name=$(create_staging_bucket)

  aws s3 cp "$LABIDE_SCRIPT" "s3://${bucket_name}/${HELPER_OBJECT}" \
    --cache-control "max-age=0" > /dev/null

  printf '%s\n' "$bucket_name"
}

generate_labide_script() {
  cat > "$LABIDE_SCRIPT" <<EOF
#!/bin/bash
# Generated by lab8_1.sh for AWS Academy Lab 8.1

set -euo pipefail

REGION="${REGION}"
CODE_URL="${CODE_URL}"
MYSQL_PUBLIC_IP="${MYSQL_PUBLIC_IP}"
LABIDE_PUBLIC_IP="${LABIDE_PUBLIC_IP}"
ECR_REPO_NAME="${ECR_REPO_NAME}"
BASE="\$HOME/environment"
NODE_DIR="\$BASE/containers/node_app/codebase_partner"
MYSQL_DIR="\$BASE/containers/mysql"

wait_for_http() {
  local url="\$1"
  local retries="\${2:-90}"
  local count=0

  until curl -fsS "\$url" > /dev/null 2>&1; do
    count=\$((count + 1))
    if [ "\$count" -ge "\$retries" ]; then
      echo "ERROR: Timed out waiting for \$url" >&2
      exit 1
    fi
    sleep 2
  done
}

echo ""
echo "===> [Task 1] Downloading lab files..."
mkdir -p "\$BASE"
cd "\$BASE"
if [ ! -f code.zip ]; then
  wget -q "\$CODE_URL" -O code.zip
fi
unzip -o code.zip > /dev/null 2>&1 || true

echo "===> [Task 1] Running setup.sh..."
chmod +x ./resources/setup.sh
./resources/setup.sh

echo "===> [Task 1] Verifying tools..."
aws --version
pip3 show boto3 > /dev/null

echo ""
echo "===> [Task 3] Preparing node_app workspace..."
mkdir -p "\$BASE/containers/node_app"
if [ ! -d "\$NODE_DIR" ]; then
  cp -R "\$BASE/resources/codebase_partner" "\$BASE/containers/node_app/"
fi

cat > "\$NODE_DIR/Dockerfile" <<'DOCKERFILE'
FROM node:11-alpine
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY . .
RUN npm install
EXPOSE 3000
CMD ["npm", "run", "start"]
DOCKERFILE

echo "===> [Task 3] Building node_app image..."
cd "\$NODE_DIR"
docker build --tag node_app .

echo "===> [Task 3] Starting node_app_1 against MysqlServerNode..."
docker stop node_app_1 2>/dev/null || true
docker rm node_app_1 2>/dev/null || true
docker run -d --name node_app_1 -p 3000:3000 -e APP_DB_HOST="\$MYSQL_PUBLIC_IP" node_app > /dev/null
wait_for_http "http://localhost:3000" 45
echo "    node_app_1 is responding on localhost:3000."

echo ""
echo "===> [Task 4] Dumping MySQL data from MysqlServerNode..."
mkdir -p "\$MYSQL_DIR"
mysqldump -P 3306 -h "\$MYSQL_PUBLIC_IP" -u nodeapp -pcoffee \
  --databases COFFEE > "\$MYSQL_DIR/my_sql.sql"
echo "    Dump created at \$MYSQL_DIR/my_sql.sql"

if grep -q 'Main' "\$MYSQL_DIR/my_sql.sql"; then
  sed -i '0,/Main/s//Container/' "\$MYSQL_DIR/my_sql.sql"
  echo "    Updated the first 'Main' occurrence in the dump to 'Container'."
fi

cat > "\$MYSQL_DIR/Dockerfile" <<'DOCKERFILE'
FROM mysql:8.0.23
COPY ./my_sql.sql /
EXPOSE 3306
DOCKERFILE

echo "===> [Task 4] Freeing unused Docker space..."
docker image prune -af > /dev/null 2>&1 || true
docker container prune -f > /dev/null 2>&1 || true

echo "===> [Task 4] Building mysql_server image..."
cd "\$MYSQL_DIR"
docker build --tag mysql_server .

echo "===> [Task 4] Starting mysql_1..."
docker stop mysql_1 2>/dev/null || true
docker rm mysql_1 2>/dev/null || true
docker run --name mysql_1 -p 3306:3306 -e MYSQL_ROOT_PASSWORD=rootpw -d mysql_server > /dev/null

echo "    Waiting for MySQL to initialize..."
for _ in \$(seq 1 36); do
  if docker exec mysql_1 mysqladmin ping -u root -prootpw --silent > /dev/null 2>&1; then
    break
  fi
  sleep 5
done

if ! docker exec mysql_1 mysqladmin ping -u root -prootpw --silent > /dev/null 2>&1; then
  echo "ERROR: mysql_1 did not become ready in time." >&2
  exit 1
fi

docker exec -i mysql_1 mysql -u root -prootpw -e "DROP DATABASE IF EXISTS COFFEE;"
sed -i '1d' "\$MYSQL_DIR/my_sql.sql"
docker exec -i mysql_1 mysql -u root -prootpw < "\$MYSQL_DIR/my_sql.sql"
docker exec -i mysql_1 mysql -u root -prootpw -e \
  "CREATE USER IF NOT EXISTS 'nodeapp' IDENTIFIED WITH mysql_native_password BY 'coffee'; GRANT ALL PRIVILEGES ON *.* TO 'nodeapp'@'%'; FLUSH PRIVILEGES;"
echo "    mysql_1 seeded and nodeapp user created."

echo ""
echo "===> [Task 5] Reconnecting node_app_1 to mysql_1..."
MYSQL_CONTAINER_IP="\$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' mysql_1)"
docker stop node_app_1 > /dev/null 2>&1 || true
docker rm node_app_1 > /dev/null 2>&1 || true
docker run -d --name node_app_1 -p 3000:3000 -e APP_DB_HOST="\$MYSQL_CONTAINER_IP" node_app > /dev/null
sleep 10
wait_for_http "http://localhost:3000" 45
echo "    node_app_1 is now using mysql_1 at \$MYSQL_CONTAINER_IP."

echo ""
echo "===> [Task 6] Pushing node_app to ECR..."
ACCOUNT_ID="\$(aws sts get-caller-identity --query Account --output text --region "\$REGION")"
ECR_REGISTRY="\${ACCOUNT_ID}.dkr.ecr.\${REGION}.amazonaws.com"

if ! aws ecr describe-repositories --repository-names "\$ECR_REPO_NAME" --region "\$REGION" > /dev/null 2>&1; then
  aws ecr create-repository --repository-name "\$ECR_REPO_NAME" --region "\$REGION" > /dev/null
fi

ECR_URI="\$(aws ecr describe-repositories --repository-names "\$ECR_REPO_NAME" --region "\$REGION" --query 'repositories[0].repositoryUri' --output text)"
aws ecr get-login-password --region "\$REGION" | docker login --username AWS --password-stdin "\$ECR_REGISTRY"
docker tag node_app:latest "\$ECR_URI:latest"
docker push "\$ECR_URI:latest"

echo ""
echo "===> [Task 6] Verifying ECR image..."
aws ecr list-images --repository-name "\$ECR_REPO_NAME" --region "\$REGION"

echo ""
echo "===> Running containers:"
docker ps

echo ""
echo "=== Lab 8.1 LabIDE setup COMPLETE ==="
echo "    App URL: http://\$LABIDE_PUBLIC_IP:3000"
echo "    ECR repo: \$ECR_URI"
EOF

  chmod +x "$LABIDE_SCRIPT"
}

echo ""
echo "==> [Task 1] Discovering lab instances..."

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text --region "$REGION")

read -r LABIDE_ID LABIDE_PUBLIC_IP LABIDE_SG <<< "$(find_instance_info '*LabIDE*,*Lab IDE*,*lab-ide*,*IDE*')"
require_value "$LABIDE_ID" "LabIDE instance ID"
require_value "$LABIDE_PUBLIC_IP" "LabIDE public IP"
require_value "$LABIDE_SG" "LabIDE security group"
echo "    LabIDE:        $LABIDE_ID ($LABIDE_PUBLIC_IP)"

read -r MYSQL_INSTANCE_ID MYSQL_PUBLIC_IP MYSQL_SG <<< "$(find_instance_info '*MysqlServerNode*,*Mysql*,*mysql*,*MySQL*')"
require_value "$MYSQL_INSTANCE_ID" "MysqlServerNode instance ID"
require_value "$MYSQL_PUBLIC_IP" "MysqlServerNode public IP"
echo "    MysqlServer:   $MYSQL_INSTANCE_ID ($MYSQL_PUBLIC_IP)"

read -r APPSERVER_ID APPSERVER_PUBLIC_IP APPSERVER_SG <<< "$(find_instance_info '*AppServerNode*,*AppServer*,*App Server*')"
if [ -n "${APPSERVER_ID:-}" ] && [ "$APPSERVER_ID" != "None" ]; then
  echo "    AppServer:     $APPSERVER_ID ($APPSERVER_PUBLIC_IP)"
else
  APPSERVER_PUBLIC_IP=""
  echo "    AppServer:     not found automatically"
fi

echo ""
echo "========================================================="
echo "*** ACTION REQUIRED BEFORE CONTINUING — TASK 2 GRADE ***"
echo "========================================================="
echo ""
echo "  You MUST add a supplier through the original AppServer"
echo "  website NOW, or you will lose 5 points on Task 2."
echo ""
if [ -n "$APPSERVER_PUBLIC_IP" ]; then
  echo "  1. Open this URL in your browser:"
  echo "     http://$APPSERVER_PUBLIC_IP"
else
  echo "  1. In the EC2 console find AppServerNode and copy its"
  echo "     public IP, then open http://<AppServerNode-ip>"
fi
echo "  2. Click 'List of suppliers' -> 'Add a new supplier'"
echo "  3. Fill in ALL fields and click Submit."
echo "  4. Confirm the record appears in the suppliers list."
echo ""
echo "  Do this NOW before pressing ENTER below."
echo "========================================================="
echo ""
read -rp "Press ENTER only after you have added a supplier on the AppServer website..."

echo ""
echo "==> [Task 3] Preparing required network access..."
MY_IP=$(curl -fsS https://checkip.amazonaws.com | tr -d '\r\n')
echo "    Your public IP: $MY_IP"
ensure_port_3000_for_my_ip "$LABIDE_SG" "${MY_IP}/32"
ensure_mysql_port_best_effort "$MYSQL_INSTANCE_ID"

echo ""
echo "==> Generating LabIDE helper script..."
generate_labide_script
echo "    Helper script: $LABIDE_SCRIPT"

HELPER_BUCKET=""
if HELPER_BUCKET=$(upload_helper_script 2>/dev/null); then
  echo "    Helper script staged through S3: s3://$HELPER_BUCKET/$HELPER_OBJECT"
else
  echo "    WARNING: Could not stage the helper script through S3."
  echo "             Use the generated local file instead: $LABIDE_SCRIPT"
fi

echo ""
echo "========================================================="
echo "Lab 8.1 Before You Run Anything"
echo "========================================================="
if [ -n "$APPSERVER_PUBLIC_IP" ]; then
  echo "1. Open the ORIGINAL AppServer website first: http://$APPSERVER_PUBLIC_IP"
  echo "2. Use the website UI to add a supplier record there."
  echo "   This is required for the Task 2 grade check."
else
  echo "1. In EC2, open AppServerNode and copy its public IP."
  echo "2. Open http://<AppServerNode-public-ip> and add a supplier there before continuing."
fi
echo "3. Only after that, open LabIDE from Details -> LabIDEURL."
echo "4. Log in with Details -> LabIDEPassword."

echo ""
echo "========================================================="
echo "Run In LabIDE (VS Code / code-server)"
echo "========================================================="
echo "Do NOT run this in the AWS Academy embedded terminal."
echo "Do NOT run this in CloudShell."
echo ""
echo "Open a terminal inside LabIDE and run these commands:"
echo ""
echo 'ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)'
echo 'REGION=$(aws configure get region 2>/dev/null || echo us-east-1)'
if [ -n "$HELPER_BUCKET" ]; then
  echo "aws s3 cp \"s3://$HELPER_BUCKET/$HELPER_OBJECT\" /tmp/lab8.sh && bash /tmp/lab8.sh"
else
  echo ""
  echo "S3 staging failed locally. Copy $LABIDE_SCRIPT into LabIDE as /tmp/lab8.sh, then run:"
  echo "bash /tmp/lab8.sh"
fi
echo ""
echo "Wait for this exact line in LabIDE before coming back:"
echo "=== Lab 8.1 LabIDE setup COMPLETE ==="
echo "========================================================="
echo ""
read -rp "Press ENTER after the LabIDE helper reports COMPLETE..."

echo ""
echo "==> Verifying ECR image..."
IMAGE_TAGS=$(aws ecr list-images --repository-name "$ECR_REPO_NAME" --region "$REGION" \
  --query "imageIds[*].imageTag" --output text 2>/dev/null || true)

if [ -n "$IMAGE_TAGS" ] && [ "$IMAGE_TAGS" != "None" ]; then
  echo "    ECR image found: $IMAGE_TAGS"
else
  echo "    WARNING: No ECR image found yet. Check the LabIDE terminal output."
fi

echo ""
echo "==> All Lab 8.1 driver steps are ready."
echo "    App URL:       http://$LABIDE_PUBLIC_IP:3000"
echo "    ECR repo name: $ECR_REPO_NAME"
